name: 一般议题
description: 任务分配记录、内容修改标记等
title: "[用户手册] "

body:
  - type: textarea
    attributes:
      label: 议题内容
      # description: 文章的主体，标题请从二级标题开始，文档风格指南请参考《贡献者指南》
      # placeholder: A clear and concise description of what the feature is, and what it will enhance or solve. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 如果你有其他信息需要说明，可以写在这里
